name: trendychef
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  google_nav_bar: ^5.0.7
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  smooth_page_indicator: ^1.2.1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  meta: ^1.16.0
  flutter_swipe_button: ^2.1.3
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.1
  url_strategy: ^0.3.0
  shimmer: ^3.0.0
  go_router: ^16.0.0
  share_plus: ^12.0.0
  path_provider: ^2.1.5
  universal_html: ^2.2.4
  video_player: ^2.10.0
  cached_network_image: ^3.4.1
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: logofont
      fonts:
        - asset: assets/fonts/Logo-font.ttf
